replicaCount: 1

image:
  repository: trivelastic
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  # Server configuration
  - name: PORT
    value: "8080"
  # Elasticsearch configuration
  - name: ES_URL
    value: ""
  - name: ES_API_KEY
    value: ""
  - name: ES_INDEX
    value: ""
  # Logging configuration
  - name: LOG_LEVEL
    value: "info"
  - name: LOG_FORMAT
    value: "json"
