apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trivelastic
  labels:
    app: trivelastic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: trivelastic
  template:
    metadata:
      labels:
        app: trivelastic
    spec:
      containers:
        - name: trivelastic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}